language: node_js
node_js:
  - "10"

os: [linux]
dist: trusty
cache: yarn

script: yarn run build

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
